#!/bin/sh
mkdir /home/dotcloud/code/logs
chmod 777 /home/dotcloud/code/logs
crontab /home/dotcloud/code/web/tflcron

python /home/dotcloud/code/setupAndBase/setupApp.py /home/dotcloud/code/config/tfl.cfg dotcloud >> /home/dotcloud/code/logs/setupApp.log 2>&1